### ISSUE TITLE
better typescript integration

### ISSUE THREAD

**Issue by vorant94** [dexie/dexie-website-old#145]
in the getting started guide in case user is using TypeScript it is advised to create custom database class extending dexie one and define table fields there like that

```typescript
// db.ts
import Dexie, { Table } from 'dexie';

export interface Friend {
  id?: number;
  name: string;
  age: number;
}

export class MySubClassedDexie extends Dexie {
  // 'friends' is added by dexie when declaring the stores()
  // We just tell the typing system this is the case
  friends!: Table<Friend>;

  constructor() {
    super('myDatabase');
    this.version(1).stores({
      friends: '++id, name, age' // Primary key and indexed props
    });
  }
}

export const db = new MySubClassedDexie();
```

I wonder why not just using global types? this way we can benefit from ts interface merging. it looks something like that somewhere in the `global.d.ts` of the project

```typescript
import 'dexie';

declare module 'dexie' {
  import { SubscriptionModel } from '@/subscriptions/models/subscription.model.ts';
  import { Table } from 'dexie';

  interface Dexie {
    subscriptions: Table<SubscriptionModel>;
  }
}
```

it will result in the same types, but will have less footprint and overall seems to be more minimal.

what do you think? If you agree with the idea I can create PR to update docs

**Comment by dfahlander** [comment]
That works but it wouldn't reflect the fact that multiple Dexie instances may exist in the same app with different set of tables. The updated [typescript docs in dexie](https://dexie.org/docs/Typescript) suggests a lighter way of extending the typings without having to subclass it:

```ts
const db = new Dexie('name') as Dexie & {
  subscriptions: Table<SubscriptionModel>; // or EntityTable<...>
};
```

dexie@5 is planned to allow a bit more sofisticated declaration: https://dexie.org/roadmap/dexie5.0#type-safe-declation-and-easier-class-mapping

**Comment by vorant94** [comment]
yeah, you totally right about multiple databases per project, I didn't think about this perspective

so it is just a question of sync of getting starter docs part with typescript part. is it ok to create PR for it or anyway since v5 introduces a new syntax this sync is something that can be ignored for now?

**Comment by dfahlander** [comment]
Please elaborate what you would like to do PR about? Is it a docs page or some code or sample in the dexie repo?

**Comment by vorant94** [comment]
I'd like to update typescript [code example](https://dexie.org/docs/Tutorial/React#using-typescript) inside **getting started** docs page so it will use the same [code example](https://dexie.org/docs/Typescript#simplest-typescript-example) as **typescript** docs page does, e.g.

```typescript
const db = new Dexie('FriendsDatabase') as Dexie & {
  friends: EntityTable<
    Friend,
    'id' // primary key "id" (for the typings only)
  >;
};
```

instead of 

```typescript
export class MySubClassedDexie extends Dexie {
  // 'friends' is added by dexie when declaring the stores()
  // We just tell the typing system this is the case
  friends!: Table<Friend>;

  constructor() {
    super('myDatabase');
    this.version(1).stores({
      friends: '++id, name, age' // Primary key and indexed props
    });
  }
}

export const db = new MySubClassedDexie();
```

as of now I refer only to react getting started, but I assume all framework specific getting started docs should be updated as well if we decide so

**Comment by dfahlander** [comment]
Please do! Thanks!
