### ISSUE TITLE
Support HTTPS

### ISSUE THREAD

**Issue by qgustavor** [dexie/dexie-website-old#33]
GitHub Pages support HTTPS on custom domains, [it just need to be enabled](https://help.github.com/articles/securing-your-github-pages-site-with-https/#enforcing-https-for-your-github-pages-site).

**Comment by dfahlander** [comment]
Thanks. I'll check it out! Currently I get certificate warning if navigating to https://dexie.org, but probably need to configure something differently in the dns.

**Comment by dfahlander** [comment]
Finally got it working. Thanks for the tip!
