### ISSUE TITLE
Docs missing for various error types

### ISSUE THREAD

**Issue by nponiros** [dexie/dexie-website-old#5]
Currently these seem to be missing:

* AbortError
* ConstraintError
* DatabaseClosedError
* DataCloneError
* DataError
* InternalError
* InvalidAccessError
* InvalidArgumentError
* InvalidStateError
* NoSuchDatabaseError
* NotFoundError
* QuotaExceededError
* ReadOnlyError
* SubTransactionError
* TimeoutError
* TransactionInactiveError
* UnknownError
* UnsupportedError
* VersionError (maybe this is the VersionChangeError?)

These errors are listed in DexieError. No clue which ones are actually relevant.

**Comment by dfahlander** [comment]
All are relevant. Keeping this issue open until done.
