### ISSUE TITLE
Unable to add event listener to 'error' event

### ISSUE THREAD

**Issue by HenryHall** [dexie/dexie-website-old#57]
**Version:** 2.0.4

In [Dexie.VersionError.md](https://dexie.org/docs/DexieErrors/Dexie.VersionError), the switch example shows some code subscribing to an error event but will throw the following error:

`Uncaught TypeError: Cannot read property 'subscribe' of undefined`

**Comment by dfahlander** [comment]
I can't see the word subscribe anywhere on the page referred to. I do not understand the question, sorry.

**Comment by HenryHall** [comment]
'error' does not appear to be an acceptable value for the first argument of the `db.on` function.

**Comment by dfahlander** [comment]
You mean this: https://dexie.org/docs/Dexie/Dexie.on.error ?

It's one of the few deprecated API:s in version 1.x. See a workaround here: https://dexie.org/docs/Deprecations#dexieonerror--dbonerror

**Comment by HenryHall** [comment]
I see, thank you for linking those other documents.  I would suggest removing or clarifying the deprecation the Dexie.on.error example on the Dexie.VersionError documentation.
