### ISSUE TITLE
Direct edit links not working

### ISSUE THREAD

**Issue by nponiros** [dexie/dexie-website-old#9]
Links which implicitly point to an index.html page point to the directory when we click on edit (For example the edit link on the home page).

The other links point to .html pages which obviously don't exist. Should point to .md pages.

This could help https://github.com/jekyll/jekyll/issues/633

**Comment by dfahlander** [comment]
Thanks! Just noticed and fixed the MD pages but not index pages.

**Comment by dfahlander** [comment]
Anyway, index pages ends up in the folder at github, so it's kind of ok anyway so far.

**Comment by nponiros** [comment]
Yeah and I think there are only 2 index pages. Home and the tutorial page. Table/Collection etc. don't use index.md

**Comment by dfahlander** [comment]
Should we close this? I mean it's not really an error to be redirected to the github repo folder anyway. For me, this is good enough.

**Comment by nponiros** [comment]
Yes, closing
