### ISSUE TITLE
Docs page for Table.each() is blank

### ISSUE THREAD

**Issue by CottageCabbage** [dexie/dexie-website-old#95]
https://dexie.org/docs/Table/Table.each()

**Comment by dfahlander** [comment]
It's referring to Collection.each(). Should it be explained better than just a referral you think?

**Comment by CottageCabbage** [comment]
If it's like `.toArray()`, where the result is the same on Collection or Table, I think there's no need? I didn't think much before creating the issue, sorry

**Comment by dfahlander** [comment]
Ok thanks 👍
